language: android
jdk: oraclejdk8
os: linux
dist: xenial
env:
    global:
        - ANDROID_API_LEVEL=30
        - ANDROID_BUILD_TOOLS_VERSION=29.0.3

install:
    - echo yes | sdkmanager "tools"
    - echo yes | sdkmanager "platforms;andoid-${ANDROID_API_LEVEL}"
android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL
        # Additional components
        - extra-android-m2repository

before_script:
    - chmod +x gradlew
    - chmod +x cicd_scripts/lint-up.rb

script:
    - ./gradlew clean assembleDebug
    - ruby cicd_scripts/lint-up.rb
